### ISSUE TITLE
Cannot bind value to numeric inputs in IE & Edge

### ISSUE THREAD

**Issue by indolering** [Polymer/polymer#3088]
`<input value="[[numeric_property]]" type="numeric">` results in a blank field in IE11 and Edge.

I'm having trouble getting either IE11 or Edge to perform any databinding on [this example jsbin](http://jsbin.com/nabotet/5/edit?html,output), but I have reproduced the issue in a fresh copy of the seed element.

IE apparently clears numeric input fields whenever it encounters a non-numeric value.  My guess is that the data binding mechanism isn't coercing the value to a number.

**Comment by JeremybellEU** [comment]
Hello @indolering 

Could you change the attribute to `value$` as described in [the section about native binding](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#native-binding). It should then become `<input value$="[[numeric_property]]" type="numeric">`. This should fix the issue you are encountering.

Please let me know if it fixed the issue for you.

**Comment by arthurevans** [comment]
Must have mistakenly closed this issue earlier while trying to look at it on the phone; my apologies.

To work in any platform other than Chrome or Opera, the jsbin needs to include the polyfills, and it needs to wait for the html imports to load before registering the element. Here's an updated jsbin:

http://jsbin.com/qawima/2/edit?html,output

This updated jsbin still shows the issue in question.

The `value` property is always a string, even on numeric inputs, so the type coercion theory doesn't seem right. In fact, I tried setting the input value manually in ready to 32 or `this.age`, and both worked fine. So I'm guessing this is some kind of timing issue.

IE 11 is horking up an exception when I try to use `value$=`. Not sure what's up with that.

@azakus can you see something I'm missing here? Looks like a legit bug to me...

**Comment by azakus** [comment]
@arthurevans That error is fixed in master with https://github.com/Polymer/polymer/pull/2673

This bin works correctly in IE 11: http://jsbin.com/rofosa/edit?html,output

**Comment by indolering** [comment]
Having this work on Chrome and Firefox but break on IE is very confusing and Polylint doesn't catch the problem either. 

@azakus Your JS bin is broken on Chrome, IE, and Edge.

Okay to close if #2673 fixes the problem.

**Comment by azakus** [comment]
@indolering Sorry my syntax was wrong for the polygit line.

This one works in both: http://jsbin.com/pinile/1/edit?html,output

**Comment by indolering** [comment]
@azakus confirmed working on Chrome, IE, and Edge.

@JeremybellEU that section of the documentation doesn't list value as an attribute requiring `$=` so I created an [issue ticket for the docs](https://github.com/Polymer/docs/issues/1448).

**Comment by arthurevans** [comment]
@azakus is there a reason we need to use `value$=` here to make IE happy? I've never had to use it for `value` elsewhere, and I'd expect a regular property binding to work in this case.

**Comment by arthurevans** [comment]
So I've confirmed as best I can that this _doesn't_ work without the `$=` on IE. 

We've never used `$=` with value before that i know of. In fact, we have property bindings to 
`value` in the docs, and in the unit tests:

https://github.com/Polymer/polymer/blob/master/test/unit/bind-elements.html#L46

Now, we appear to need it for `<input type="number">` (but not for regular text inputs, as above).

Is this a regression or a corner case?

**Comment by JeremybellEU** [comment]
Binding to the `value` attribute of an `input` element is problematic due to IE throwing exceptions when values does not match the expected type.

The test linked by @arthurevans does not specify a type and therefore takes the default `text` type. This matches the binding and therefore does not break. If however it type would be number, the binding does not match a number and therefore IE throws an exception.

When using `value$`, this original assignment is not evaluated (since `value` is not defined). Then Polymer calculates the correct value via the binding and explicitly sets the attribute `value` to the outcome.

Concluding: to prevent any exception from happening, use `value$` (and for all other native attributes).

#2673 fixed a regression regarding `input` with `value$`, but this is now fixed on master.

**Comment by arthurevans** [comment]
@JeremybellEU you're right that this is an issue with IE. I was hoping to get an idea from @azakus or @sorvell whether there was some way the library could work around this. 

Since `value$=` can't be used for two-way binding, it's a big disadvantage here, and if we're not careful risks creating a long-running confusion about whether it's necessary. In every other use case, using `value$=` is wrong.

**If we can't fix this in the library in the near term**, I think we should add a note to the "binding to native inputs" section, mentioning the limitation on typed inputs on IE, and giving both workarounds (use `value$=` or use `<iron-input>`).

**Comment by JeremybellEU** [comment]
It might be possible to, whenever Polymer encounters a `value$` (or a different native attribute) to bind a listener to the `onchange` attribute of the element.
http://jsbin.com/xapurovuqu/edit?html,console,output

This does have some caveats:
* You don't want to always trigger such a change
* It only triggers upon hitting enter => maybe to bind to a different event
* The value is a string, so conversion to the actual type is required.

Maybe this would solve such problems and also enable two-binding of native attributes. Although they are workarounds and might introduce more problems than they fix.

**Comment by arthurevans** [comment]
@JeremybellEU there are a few, specific native properties where attribute binding (`$=`) is generally required. _value isn't one of them_, except in this one, specific case, to work around a bug in IE.

What you're suggesting is to make the semantics of `$=` work completely differently, which is not what I'm asking about.

I'm asking whether we can make the standard property bindings, `value="[[someProp]]"` and `value="{{someProp::input}}"` work on IE.

There's no need for Polymer to convert the type (in the general case). An input's `value` is a string by definition. The problem here is that for `type="number"` (at least, I haven't tested any others), IE is imposing a nonstandard restriction.

**Comment by JeremybellEU** [comment]
Okay I misunderstood. Hopefully the core developers can jump in and develop a solution!

**Comment by arthurevans** [comment]
:+1:

**Comment by indolering** [comment]
This seems like a lot of trouble to go through for such a small edgecase.  If you can get the Edge developers to fix this one tiny difference, then you could just leave it as-is for numeric input values.

**Comment by arthurevans** [comment]
Ping @sorvell @azakus any way we could work around this IE bug?

**Comment by indolering** [comment]
@arthurevans It's my understanding that the bug has been fixed but hasn't been included in a release yet.  I've been pinging devs on Slack and a release will happen as soon as their unit tests start clearing.

**Comment by arthurevans** [comment]
@indolering I don't think this bug has been fixed. Or, it's half-fixed more accurately.

With 1.2.4, it looks like you can use `value$="[[age]]"`. But you still can't use `value="{{age}}"` or 
`value="[[age]]"` on IE. 

I think that given the number of high priority issues and the relative risk/reward here, we should probably add a note to the document that for binding number inputs, you can either choose broken in IE, or half-broken everywhere. :crying_cat_face:

**Comment by indolering** [comment]
> But you still can't use value="{{age}}" or value="[[age]]" on IE.

Can you use `value$="{{age}}"`?

Also, how does Github not have an IE glue eater emoticon?

**Comment by indolering** [comment]
Just a heads up, using `value$=[[param]]` severely broke data-binding in my element (including Firefox and Chrome).  I'm having a hard time isolating/reproducing the bug but I would strongly suggest against updating the documentation for now.  

I'm using iron-list, would love suggestions on what to look for.

**Comment by arthurevans** [comment]
What is breaking? Can you add a brief repro?

**Comment by indolering** [comment]
@arthurevans I'm having a hard time replicating the issue in a naive re-implementation in JSBin.  But it appears as if iron-list has some deficits in it's data binding system ... so it's probably safe to update the documentation.  Given that people are probably experiencing subtle breakage on IE/Edge, it's probably better to update the docs now than to wait.

Sadly, I'm coming close to not being allowed to work on this anymore.  It's proprietary code, so I can't share it publicly but I can send a copy if you shoot me an email: zachlym@indolering.com.

**Comment by indolering** [comment]
@arthurevans, you mentioned `<iron-input>` as an alternative but [it doesn't have a `number` type property](https://github.com/PolymerElements/iron-input/issues/67).  Did you just not know about this or were you thinking it would be easier given the custom validator functionality?  Not sure if we should put it in the documentation until there is a numeric input option.

**Comment by indolering** [comment]
I finally tracked down the bugs I had with `iron-list`, combination of custom `value$` reporting change events in response to non-user interaction and altering the path notification syntax.

@azakus feel free to close unless you want to keep it open for discussion on how to enable 2-way binding.
