### ISSUE TITLE
notifySplices fails to notify about changes in array of primitives

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#3377]
I have an array of Strings that's being changed:

``` js
var model = {
    people: [
        "Alice",
        "Bob"
    ]
};
// ...
model.people[0] = "Anna";
```

So, I would like to notify my `dom-bind` about this change using `notifySplices`:

``` js
domBind.notifySplices('organization.people', [{
    index: 0,
    removed: removed,
    addedCount: 1,
    object: model.people,
    type: 'splice'
}]);
```

Live example here
http://jsbin.com/kocowalimi/1/edit?html,console,output

In result, entire content of `dom-repeat` disappears and throws an error:

```
"TypeError: Cannot read property 'isPlaceholder' of undefined
    at dom-repeat.Polymer._detachInstance (http://polygit.org/components/polymer/polymer.html:4415:10)
    at dom-repeat.Polymer._detachAndRemoveInstance (http://polygit.org/components/polymer/polymer.html:4430:17)
    at dom-repeat.Polymer._applySplicesArrayOrder (http://polygit.org/components/polymer/polymer.html:4406:6)
    at dom-repeat.Polymer._render (http://polygit.org/components/polymer/polymer.html:4259:6)
    at Object.Debouncer.complete (http://polygit.org/components/polymer/polymer-mini.html:2099:15)
    at boundComplete (http://polygit.org/components/polymer/polymer-mini.html:2078:6)
    at Object.Polymer.Async._atEndOfMicrotask (http://polygit.org/components/polymer/polymer-mini.html:2055:1)
    at MutationObserver.window.MutationObserver.observe.characterData (http://polygit.org/components/polymer/polymer-mini.html:2070:15)"
```

If I change string names to objects like `{name: "Alice"}..` it works, but I cannot change my database models, just to fit this UI.

**Comment by d1manson** [comment]
I'm trying to understand `notifySplices` myself, the docs aren't super clear.  Reading the code for `dom-repeat` is vaguely helpful, but I haven't found everything I needed yet.

@tomalec - I noticed one actual mistake in your jsbin - you need to pass an array as the second arg to `notifySplices`, rather than a raw object.   But that alone doesn't make it work. 

Here's a link to my edit of your jsbin - http://jsbin.com/juwiyodefu/1/edit?html,console,output. For simplicity I made `people` a property of the model directly, rather than a child of `organisation`, though that also didn't help.  However I did find the following:

```javascript
// This does work...
var removed = domBind.people.splice(0, 1, "Anna") 

// This does *not* work
var removed = domBind.people[0];
domBind.people[0] = "Anna";
```

**Comment by tomalec** [comment]
Thanks @d1manson, I have updated examples at OP
I'm also happy to hear that, I'm not the only one struggling with this problem ;)

**Comment by arthurevans** [comment]
The `notifySplices` API is for notifying Polymer of changes that _have already been made to an array_, which didn't use the built-in Polymer array mutation methods. (`Polymer.Base.push`, `pop`, `splice`, etc.) These methods are available on any Polymer element, and also on `dom-bind`.

@d1manson's sample does this by calling `domBind.people.splice` ... This sample is basically the same as the example in the API docs:
https://www.polymer-project.org/1.0/api/#Polymer.Base:method-notifySplices

If you just want to change a value in the array, you can also use `set`, as in:

`domBind.set('people.0', 'Anna');`

If you've already changed the array (or more to the point, if you have a third-party library that's changing the data), you need to notify Polymer after the fact using `notifyPath` or `notifySplices`. 

Here's a version of the original JSBin that shows off several of these techniques.

http://jsbin.com/xevije/edit?html,console,output

So it doesn't seem like there's a bug here, except perhaps that the API docs for `notifySplices` could be improved? (Notably, the basic description could be clearer about the fact that `notifySplices` is an _alternative_ to using the built-in dom manipulation methods like `this.splice`, and should be used to notify Polymer of changes _that have already happened_.)

**Comment by d1manson** [comment]
Yeah, the docs for `notifySplices` aren't very clear.

 Is it correct to use `removed: [{name: 'Todd'}]`, i.e. not to use the original object, but to make a new one that happens to have the same data?  As far as I can tell, the whole array machinery is backed by a `WeakMap` which uses objects as keys, so it wouldn't make much sense to provide a new object?  Although perhaps everything could still work using just the indices?

Also, what exactly does it mean by:

> splice records must be normalized such that they are reported in index order

In particular, how are you supposed to handle moving elements?  I read somewhere (I forget now where exactly) that you can't have the same element in the array in multiple locations simultaneously. So if you want to move element 5 to position 2, you need to first splice it out and then splice it back in at the new location...but apparently notifySplices wants splice records in index order, i.e. the "splice in at index 2" record should come first...but then you're back to having the entry in the array multiple times.

**Comment by arthurevans** [comment]
To the first question, I think the answer is _no_, you need to use the original object.

To the second question, I defer to @kevinpschaaf, but my testing suggests that yes, you should report those operations to notifySplices in index order. Here's a jsbin:

http://jsbin.com/zoyebe/edit?html,output

Your array doesn't actually end up with duplicate entries, and the code that handles `notifySplices` is prepared for this kind of thing.

If you're curious, the internal collection is updated in [_applysplices](https://github.com/Polymer/polymer/blob/441103159f7b9fc9af567b2caea145de21a9576d/src/lib/collection.html#L134). It took some head-scratching on my part, but I see how it handles your case. I think.

Hope that helps.

**Comment by d1manson** [comment]
wait, but in your jsbin you give the operations as `index: 3`, then `index: 1`...which isn't what I'd call "index order", but maybe I've misunderstood?

**Comment by d1manson** [comment]
P.S. Thanks for looking into this!

**Comment by arthurevans** [comment]
Oops... Heh. Right you are--I realized I'd written the example backwards (moving something from 0 to 3 instead of vice versa) and edited it quickly. 

I've fixed that, and now they're in index order (note since the added is first, the removal is now `index: 4` since that's where the removed item _would be_ if the operations were actually done in this order (which I believe is part of what falls into the "normalized" category).

Why the first example worked... Again I defer to @kevinpschaaf ... I think if they aren't passed in index order there are various potential pitfalls.

**Comment by d1manson** [comment]
Ok, well it's looking promising then!

If @kevinpschaaf can gives us the full rundown that would be nice, and I guess the docs ought to be fleshed out a bit to make this all clearer.

**Comment by tomalec** [comment]
@arthurevans Why did said  that I should use `notifyPath` not `notifySplices` for replacing an array item? (at http://jsbin.com/xevije/edit?html,console,output)
```js
// this is equivalent to the two steps:
// domBind.people[1] = "Bobby";
// domBind.notifyPath("people.1", "Bobby");
```

As I have already discovered in other issue - https://github.com/Polymer/polymer/issues/2540, and from what I get from latest docs: For replacing an array element which is object I need to use `notifySplices`.

Is there a hidden rule that "To notify the changes to an array of objects, you shall use `notifySplices`, but to notify the changes to an array of primitives, you shall use `notifyPath`" ?
If so I found it very inconsistent. Plus, what about arrays of primitives **and** objects?

Moreover neither `notifyPath` nor `notifySplices` works in my case 
http://jsbin.com/niviworotu/1/edit?html,console,output
http://jsbin.com/kocowalimi/1/edit?html,console,output
which is just to notify about  replacing the firs element of an array of primitives.

**Comment by rsORAU** [comment]
I believe that I am having a similar issue with notifySplices causing an error when trying to use the Polymer array mutations functions and then updating the display.  It does however make the manipulation to the array and then update the display, but it still throws an error.  I tried using the suggested arrayItem helper method and just accessing the element directly, but it was giving me errors for trying to use the 'this.myArray.*.base[idx]' syntax.  Does anyone have any ideas for workarounds?

**Comment by tomalec** [comment]
Sorry, my bad, that was my bug - again "`removed` should be an array` :no_mouth:. Fixed use case is here http://jsbin.com/fakuxo/edit?html,console,output

@rsORAU  do you still have any problems with it? 
If not, I think we can close this issue.

**Comment by tomalec** [comment]
I have found another problem with arrays of primitives, that may be related https://github.com/Polymer/polymer/issues/3682

**Comment by rsORAU** [comment]
I came up with a workaround for my specific use case, using instead notifyPath() outside of any async calls.  However, this is not an ideal solution to be restricted from being able to access specific elements in an array, even with the Polymer array wrapper methods.  

A more specific description of my workaround will follow.

**Comment by TimvdLippe** [comment]
This was fixed with #3970 in Polymer 2: http://jsbin.com/budocaxeru/edit?html,console,output
