### ISSUE TITLE
Polymer 2.0 having Browser compatibility issue with IE11,IEedge & Mozilla. The SHOP Progressive app Demo itself not rendering properly in other browsers except Chrome even though enabled Pollyfills. Could any one can help us on this issue.. As we are planing to use Polymer 2.0 to build web application so kindly advice.

### ISSUE THREAD

**Issue by ananth4u** [Polymer/polymer#4787]
![issue papertabs missing](https://user-images.githubusercontent.com/11664858/29169810-90bfd886-7df3-11e7-9dc8-47eee38f4296.PNG) 

#### Live Demo

http://jsbin.com/luhaxab/1/edit

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions

- Polymer: vX.X.X
- webcomponents: vX.X.X

**Comment by web-padawan** [comment]
1. I don't experience any problems with Shop in Firefox, neither Safari 9 (just a bit slow)
2. Safari 8 is no longer supported
3. your JSBin is not expected to work in IE11 and Safari 9 without `babel` transpilation.
4. there are several issues related to IE, especially [this one](https://github.com/webcomponents/shadydom/issues/168)

**Comment by TimvdLippe** [comment]
@frankiefu Could you confirm/deny that shop is working in IE and Edge?

**Comment by frankiefu** [comment]
Afaik It works in Edge and IE11. There was a [Shady CSS issue](https://github.com/webcomponents/shadycss/issues/111) but it should be fixed now.

**Comment by spyhole** [comment]
in safari version 10.1.2. it is the result.
![bug1](https://user-images.githubusercontent.com/1698342/29395548-1e294810-8344-11e7-8f06-6ec36a1ac2b4.png)

**Comment by spyhole** [comment]
ok. a little show. but it shows in safari.

**Comment by TimvdLippe** [comment]
I just tested Shop, it works in Firefox and Edge, but it does not work in IE. @frankiefu is investigating IE right now.

**Comment by spyhole** [comment]
thx @TimvdLippe and @frankiefu

**Comment by frankiefu** [comment]
Just tested on the latest and found an issue when using es5-bundled build on IE11. I believe is related to this: https://github.com/Polymer/polymer-cli/issues/856

**Comment by web-padawan** [comment]
@TimvdLippe would you mind adding `IE11` label for this repo BTW? There is an `ie10` one which could be removed (since it is no longer supported)

Tagging all IE11 issues would help us developers to check if the bug is already filed, as well as to decide whether 2.0 is *really* production ready or not.

**Comment by TimvdLippe** [comment]
@web-padawan Done :smile:

**Comment by LarsDenBakker** [comment]
We are running into the same issues for our app, and see the same error for the shop on IE11. Any update on this? It's blocking our Polymer 2 upgrade.

**Comment by web-padawan** [comment]
@tjsavage @sorvell as you can see, many users complain here and there (mostly in slack channel) about poor IE 11 support for 2.0. There are several issues which look critical once the app grows:

* [not inspectable elements](https://github.com/webcomponents/shadydom/issues/117) opened 23 mar
* [shadydom performance](https://github.com/webcomponents/shadydom/issues/155) opened 25 may

And there are more, e. g. broken Promise polyfill [issue](https://github.com/webcomponents/webcomponentsjs/issues/837)  which was fixed recently.

I must say it is still much better than it used to be as of 0.5, but not very much progress since 1.x (where occasional crashes happen as well as weird errors like #4455).

So, is there any official opinion regarding IE11 support? How much should it considered stable?
The blog post summarizing known limitations (no way for `<template>` in `<table>` etc) and bugs would be nice.

**Comment by keanulee** [comment]
Update: For local development Shop is working on IE11, Edge, and Firefox with the latest releases of polymer, shadycss, and webcomponentsjs:

```
├─┬ polymer#2.0.2
│ ├── shadycss#1.0.5
│ └── webcomponentsjs#1.0.11
```

`polymer serve` can be used to serve the shop/ directory directly, or you can statically serve the contents of build/es5-bundled/ after doing a `polymer build`.

![image](https://user-images.githubusercontent.com/1319720/30499335-ecb13e82-9a0e-11e7-90bf-d79f009a4907.png)

For deployment, there is a small issue with iron-location (used by app-route) that is affecting IE11 when Shop is on a host with no specified port. See https://github.com/PolymerElements/iron-location/issues/93 for more details, but this doesn't affect the inital load.

**Comment by LarsDenBakker** [comment]
@keanulee strange, my experience is different. I will test again and make sure I am on the same version of the dependencies. Have you tried reloading the shop on IE11 a few times with console open?

**Comment by LarsDenBakker** [comment]
@keanulee I just did another test run, still having the same issues.

I am on a MacBook Pro running Sierra. I am using Windows 7 IE11 virtualbox image from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/. I have had the same issue on a regular windows laptop as well.

I use the latest shop from the master branch of https://github.com/Polymer/shop. Polymer 2.0.2,  webcomponentsjs 1.0.11, shadycss 1.0.5. Both the built and unbuilt version crash for me.

The crash happens more often with the dev tools opened. With the dev tools closed it happens around 1 out of 10. The app stops loading halfway when it happens:

No content:
![screen shot 2017-09-16 at 5 10 53 pm](https://user-images.githubusercontent.com/11994993/30513405-e5971ef6-9b02-11e7-8eee-a7e75d3a7aeb.png)

No nav bar:
![screen shot 2017-09-16 at 5 11 01 pm](https://user-images.githubusercontent.com/11994993/30513406-eb48dcc2-9b02-11e7-9227-fdd67f2a9523.png)

Errors vary, some snippets:


![screen shot 2017-09-16 at 5 09 19 pm](https://user-images.githubusercontent.com/11994993/30513415-1d5f52fe-9b03-11e7-9dcb-93555bee3849.png)
![screen shot 2017-09-16 at 5 08 59 pm](https://user-images.githubusercontent.com/11994993/30513417-21415f5c-9b03-11e7-8e74-45874e8b6bf6.png)
![screen shot 2017-09-16 at 5 08 12 pm](https://user-images.githubusercontent.com/11994993/30513419-244abf4a-9b03-11e7-8e21-0927a83ba3e9.png)
![screen shot 2017-09-16 at 5 07 59 pm](https://user-images.githubusercontent.com/11994993/30513420-26e0646c-9b03-11e7-8aa5-c1ae40a73a5b.png)
![screen shot 2017-09-16 at 5 07 49 pm](https://user-images.githubusercontent.com/11994993/30513423-298340cc-9b03-11e7-8aa6-dc57dde2ce17.png)
![screen shot 2017-09-16 at 5 09 36 pm](https://user-images.githubusercontent.com/11994993/30513413-1aee25e0-9b03-11e7-9597-d41a7b85a613.png)
![screen shot 2017-09-16 at 5 07 06 pm](https://user-images.githubusercontent.com/11994993/30513424-2d05e0c4-9b03-11e7-8490-c7fc3e863a28.png)
![screen shot 2017-09-16 at 5 06 56 pm](https://user-images.githubusercontent.com/11994993/30513425-2f578ca6-9b03-11e7-90b5-4c558f52b9be.png)

I know these errors are probably not related to the shop itself, but it is the best reference application that somewhat represents a real production application.

**Comment by Westbrook** [comment]
I'd suggest we collect the specific sub version of each IE11 instance people are running these tests against. Each OS has a different current and sometimes final version, and it's also hard to say whether the IE11 you are using is actually up to that level depending on the testing environment. I've seen very specific differences between various releases, even at the subversion and bug fix number, so it'll go a long way to clarifying this line of conversation.

**Comment by LarsDenBakker** [comment]
Good point. In my case I am running IE 11.0.9600.17420, Update version 11.0.14

**Comment by LarsDenBakker** [comment]
Update: Just tested the same setup on Windows 10 IE 11.540.15063.0 Update Versions 11.0.45 and while I do occasionally get the same errors, it occurs far less. In 50 tries I got it perhaps twice.

**Comment by keanulee** [comment]
@LarsDenBakker Try updating IE on the Win 7 VM - seems to be working fine with 11.0.9600.18792 / Update version 11.0.46

**Comment by azakus** [comment]
So, it seems that IE 11.0.9600.18792 is the most up to date version of IE 11 on Windows 7 (after updating with the 60+ updates that this VM I'm using needed), and the shop app seems to be working correctly after 10+ reloads.

![screen shot 2017-09-18 at 11 10 26 am](https://user-images.githubusercontent.com/46725/30557104-03bb17ce-9c62-11e7-83a4-e2b1d1cee86a.png)

IE 11.0.9600.17420 seems to be the version that shipped with Windows 7 SP1, from 2014.

**Comment by LarsDenBakker** [comment]
Thanks for the updates guys. After updating my VM to IE 11.0.9600.18792 it is definitely more stable, but about 1 in 20 loads I still ge 'unable to get property '__catchall' of undefined or null reference'. The other errors are gone though. Seems to be similar to: https://github.com/webcomponents/shadydom/issues/168

What’s the official policy on IE11 sub versions? IE 11.0.9600.17420 seems to be installed on at least the laptops I tested at our company, and it’s the default on the VM provided by microsoft and browserstack as well.

**Comment by TimvdLippe** [comment]
I think we support the latest version of IE, just like the other browsers we support. I am inclined to close this particular issue in favor of https://github.com/webcomponents/shadydom/issues/168 which seems to be the last issue with IE. @azakus maybe you can take a look at that one to fix all IE11 issues? It seems that it is related to `slot` (https://github.com/vaadin/vaadin-board/pull/69/files and https://github.com/webcomponents/shadydom/issues/168#issuecomment-320335395)

**Comment by graynorton** [comment]
There's now a pull request open for webcomponents/shadydom#168. Let's get that integrated and see if it clears up the remaining failures on newer IE 11 releases (e.g. IE 11.0.9600.18792).

With respect to older releases, we’d appreciate any concrete information that our enterprise-focused partners can provide to help us better understand the real-world situation with respect to IE 11 subversion penetration. Hard data would be great, but anything more than the limited picture currently painted here would be welcomed.

There’s a significant cost involved in investigating and attempting to address sporadically reproducible issues on a version of IE that is now several years old and many official MS updates behind. Prioritizing this work will require compelling evidence that it’s required.

**Comment by graynorton** [comment]
@LarsDenBakker, we cut a new release of the polyfills last week with the fix for webcomponents/shadydom#168.

When you have a chance, can you test again to see what issues you're still observing on IE 11? Our expectation is that you'd see no errors in the latest IE 11 release. It would be great to confirm that, and also to get an updated report on what you see in older IE 11 releases now that this particular issue has been addressed.

Thanks!

**Comment by jab** [comment]
@graynorton, I just left what seems like a relevant comment at https://github.com/webcomponents/custom-elements/issues/103#issuecomment-333709002 (I'm using PSK2) and then saw this - I'll follow here now too. (Just shared access to the code for that site  (https://uproxy.github.io/uproxy.org/) with you too in case it's helpful for testing)

**Comment by ggriffithsIDBS** [comment]
I found this thread through https://github.com/webcomponents/shadydom/issues/117

Im having issues on Edge/IE 11 where elements seem to be ignoring ShadowDOM styling in certain scenarios. In my screenshot it can be observed that the contents of the ShadowDOM for my element is outside of the HTML node.

Im not sure this is related or not. This seems to occur when I used the this.async utils in my Hybrid elements on Polymer 2.0

Im seeing this when running a hybrid element through the Polymer CLI using Polymer 2.1.1 and WebComponentsjs  1.0.14
![image](https://user-images.githubusercontent.com/30403877/31176356-7e814352-a90a-11e7-807e-2dce4db22b1a.png)

**Comment by ruud** [comment]
@graynorton , I am a colleague of Lars Den Bakker. The webcomponents/shadydom#168 fixed the __catchall issues for us, but introduced a new one, unfortunately:

- 1. Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node. bower_components/webcomponentsjs/webcomponents-lite.js (bower_components/webcomponentsjs/webcomponents-lite.js) in insertBefore$1 at line 3535:9. This is using the unminified version of WebcomponentJS

**Comment by ruud** [comment]
When I upgrade the version of IE 11 to the latest version: IE 11.0.9600.18816 I get the '__catchall' issue again:

<img width="1009" alt="screen shot 2017-10-16 at 10 44 24 pm" src="https://user-images.githubusercontent.com/28245/31634433-c7ac3cb8-b2c3-11e7-8702-164288d67377.png">
